import Image from 'next/image'
import { Inter } from 'next/font/google'
import HomePage from './components/homePage/homePage'
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

//destructuring de la data que retorna la función de la linea 23. 
export default function Home({data}) {
  return (
    <div className="bg-fixed bg-center bg-cover">
    <Head>
      <title>Song - Challenge</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HomePage data={data}/>
  </div>
  )
}

//fetch a base de datos interna: ../data/data.json
export async function getServerSideProps() {

  const { allChallenges } = await import("../data/data.json");

  // console.log("allChallenges: ", allChallenges)
  
  return {
    props: {
      data: allChallenges,
    },
  };
}