# Generated by Django 3.1.2 on 2020-10-01 13:52

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


def create_default_superuser(apps, schema_editor):
    # User = apps.get_model('accounts', 'CustomUser')

    # if not User.objects.filter(is_superuser=True).exists():
    #     u = User.objects.create_superuser(
    #         username='admin', password='4321Admin')
    #     u.save()
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_superuser),
    ]
