import Head from "next/head";
import Landing from "@component/components/landing/landing";

export default function Home() {
  return (
    <>
      <Head>
        <title>Song - Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </>
  );
}
