# Generated by Django 4.2 on 2023-06-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tempo",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="songidea",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="songidea",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
